//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.05 at 06:43:23 PM CEST 
//


package hr.kbratko.soapcountries.schema;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;
import lombok.AccessLevel;
import lombok.NoArgsConstructor;

@XmlType(name = Currency.Constants.xmlTypeName)
@XmlEnum
public enum Currency {

  GBP,
  EUR,
  PLN;

  public static Currency fromValue(String value) {
    return valueOf(value);
  }

  public String value() {
    return name();
  }

  @NoArgsConstructor(access = AccessLevel.PRIVATE)
  public static class Constants {

    public static final String xmlTypeName = "currency";

  }

}
