//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.05 at 06:43:23 PM CEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.kbratko.hr/soapcountries/schema", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package hr.kbratko.soapcountries.schema;
